### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by corneel27** [robertklep/nefit-easy-cli#1]
Hello Robert,

I tested your project, I get a Syntaxerror:
SyntaxError: Unexpected token �
    at Object.parse (native)
    at /usr/lib/node_modules/nefit-easy-cli/node_modules/nefit-easy-core/lib/index.js:172:26
    at tryCatcher (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/promise.js:674:18)
    at Async._drainQueue (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate](/usr/lib/node_modules/nefit-easy-cli/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

What am i doing wrong?
Have i missed an update of a module?

Thanks in advance,
Regards, Cees van Beek

**Comment by robertklep** [comment]
It probably means that the messages that were sent by the backend couldn't be decrypted due to invalid credentials. You should make sure that all three credentials (serial number, access key and password) are valid.

**Comment by corneel27** [comment]
Ichecked it again and all is OK.
I used an exclamation ("!") in the password, could that be the problem?

**Comment by corneel27** [comment]
I have tested it: changed my password (without exclamation) and now it worked!!

**Comment by corneel27** [comment]
Thank you for your cooperation!

**Comment by robertklep** [comment]
@Cees-van-Beek thanks for checking :-) I'll have to see if the app does anything special with those characters, perhaps they have to be encoded in some way.

**Comment by corneel27** [comment]
I am not an js-programmer, but in php there is something like urlencode. I tried it with quotation-marks(for instance --password="password!") but same error.

**Comment by robertklep** [comment]
I just realized that if you're using `!` unescaped, it might get expanded by your shell.

If you're okay with some more testing, try changing back to the old password and use this:

```
--password='password!'
```

(single quotes instead of double)

**Comment by corneel27** [comment]
Singles quotes doesn't work eather

**Comment by robertklep** [comment]
@Cees-van-Beek okay, thanks for testing. I'll investigate at some later point (here's the related issue: robertklep/nefit-easy-core#7).
